# ---------------------------------------------------------------------------
# Redis Module — ElastiCache Redis 7.x for Decision Stack
# ---------------------------------------------------------------------------
# Uses: rate limits, dedup, pub/sub, LLM token metering,
#       WebSocket session state, notification queues.
# Security: encryption at rest (KMS CMK) + in transit (TLS).
# Network: private subnets only, no 0.0.0.0/0 ingress.
# ---------------------------------------------------------------------------

locals {
  common_tags = merge(
    {
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "terraform"
    },
    var.tags
  )
}

# ---------------------------------------------------------------------------
# ElastiCache Parameter Group
# ---------------------------------------------------------------------------
resource "aws_elasticache_parameter_group" "main" {
  name   = "${var.project_name}-${var.environment}-redis-params"
  family = var.parameter_group_family
  description = "Parameter group for ${var.project_name} ${var.environment}"

  # Enable keyspace notifications for pub/sub patterns
  parameter {
    name  = "notify-keyspace-events"
    value = "Ex"
  }

  # Max memory policy — evict keys when full
  parameter {
    name  = "maxmemory-policy"
    value = "allkeys-lru"
  }

  tags = local.common_tags

  lifecycle {
    create_before_destroy = true
  }
}

# ---------------------------------------------------------------------------
# ElastiCache Security Group — private subnets only
# ---------------------------------------------------------------------------
resource "aws_security_group" "redis" {
  name_prefix = "${var.project_name}-${var.environment}-redis-"
  description = "Security group for ElastiCache Redis — private subnets only"
  vpc_id      = var.vpc_id

  ingress {
    description = "Redis from private subnets"
    from_port   = var.port
    to_port     = var.port
    protocol    = "tcp"
    cidr_blocks = var.private_subnet_cidrs
  }

  # No ingress from 0.0.0.0/0 — enforced invariant

  egress {
    description = "Allow all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = []
  }

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-${var.environment}-redis"
  })

  lifecycle {
    create_before_destroy = true
  }
}

# ---------------------------------------------------------------------------
# ElastiCache Replication Group (Redis)
# ---------------------------------------------------------------------------
resource "aws_elasticache_replication_group" "main" {
  replication_group_id = "${var.project_name}-${var.environment}"
  description          = "Redis for ${var.project_name} ${var.environment}"

  # Engine
  engine             = "redis"
  engine_version     = var.engine_version
  node_type          = var.node_type
  num_cache_clusters = var.num_cache_nodes
  port               = var.port

  # Network
  subnet_group_name  = var.subnet_group_name
  security_group_ids = [aws_security_group.redis.id]

  # Parameter group
  parameter_group_name = aws_elasticache_parameter_group.main.name

  # Encryption — both at rest and in transit
  at_rest_encryption_enabled  = var.at_rest_encryption_enabled
  kms_key_id                  = var.at_rest_encryption_enabled ? var.kms_key_arn : null
  transit_encryption_enabled  = var.transit_encryption_enabled
  transit_encryption_mode     = var.transit_encryption_enabled ? "preferred" : null

  # Failover (auto-failover requires num_cache_nodes >= 2)
  automatic_failover_enabled = var.automatic_failover_enabled && var.num_cache_nodes >= 2

  # Maintenance
  auto_minor_version_upgrade = var.auto_minor_version_upgrade
  apply_immediately          = var.apply_immediately
  maintenance_window         = var.maintenance_window
  snapshot_window            = var.snapshot_window
  snapshot_retention_limit   = var.snapshot_retention_limit

  # No cluster mode (single shard as specified)
  data_tiering_enabled = false

  tags = local.common_tags
}

# ---------------------------------------------------------------------------
# Secrets Manager — Store Redis auth token
# ---------------------------------------------------------------------------
# Auth token is auto-generated by ElastiCache when transit encryption is enabled
# We store the connection info in Secrets Manager for application retrieval

resource "random_password" "redis_auth" {
  count   = var.transit_encryption_enabled ? 1 : 0
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "redis" {
  name                    = "${var.project_name}/${var.environment}/redis/auth"
  description             = "ElastiCache Redis credentials for ${var.project_name} ${var.environment}"
  kms_key_id              = var.kms_key_arn
  recovery_window_in_days = var.environment == "prod" ? 30 : 7

  tags = local.common_tags
}

resource "aws_secretsmanager_secret_version" "redis" {
  secret_id = aws_secretsmanager_secret.redis.id
  secret_string = jsonencode({
    host               = aws_elasticache_replication_group.main.primary_endpoint_address
    port               = var.port
    reader_endpoint    = aws_elasticache_replication_group.main.reader_endpoint_address
    auth_token         = var.transit_encryption_enabled && length(random_password.redis_auth) > 0 ? random_password.redis_auth[0].result : ""
    transit_encryption = var.transit_encryption_enabled
  })
}
