"""
Event envelope types for NATS JetStream messaging.

Defines the dataclasses used for:
- IntelligenceCompressEvent: consumed from "intelligence.compress"
- CreateCardEvent: published to downstream services
"""

from dataclasses import dataclass, field
from typing import List
from uuid import UUID, uuid4


@dataclass
class IntelligenceCompressEvent:
    """
    Inbound event from the upstream compression trigger.

    Signals that a batch of raw emails has been identified for
    compression and card generation.
    """

    event_id: UUID
    user_id: UUID
    thread_id: UUID
    raw_email_ids: List[UUID]
    priority_score: float
    source: str  # "gmail" | "outlook"


@dataclass
class CreateCardEvent:
    """
    Outbound event produced after successful compression.

    Notifies downstream services that a new decision card is
    available for user review.
    """

    user_id: UUID
    thread_id: UUID
    card_id: UUID  # generated by compression service
    card_state: str = "pending"
    urgency_score: float = 0.0
